# File melder/melder_ftoa.cpp.praat
# Generated by test/createPraatTests.praat
# Tue Apr  2 15:30:07 2019

assert string$ (1000000000000) = "1000000000000"
assert string$ (undefined) = "--undefined--"

appendInfoLine: "melder/melder_ftoa.cpp.praat", " OK"
