# File melder/melder_ftoa.cpp.praat
# Generated by test/createPraatTests.praat
# Sun Apr  5 13:16:21 2020

assert string$ (1000000000000) = "1000000000000"
assert string$ (undefined) = "--undefined--"

appendInfoLine: "melder/melder_ftoa.cpp.praat", " OK"
