# File melder/VEC.cpp.praat
# Generated by test/createPraatTests.praat

assert from_to_count# (0, 10, 5) = { 0, 2.5, 5, 7.5, 10 }

assert between_count# (0, 10, 5) = { 1, 3, 5, 7, 9 }

appendInfoLine: "melder/VEC.cpp.praat", " OK"
