# FFNet/SConscript
# 
#  Copyright (C) 1993-2005 David Weenink
# 
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or (at
#  your option) any later version.
# 
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
# 
# 
# 
#  djmw 20050916

sources = Split("""
	FFNet.c
	FFNet_Eigen.c FFNet_Matrix.c FFNet_Pattern.c
	FFNet_Activation_Categories.c FFNet_Pattern_Activation.c
	FFNet_Pattern_Categories.c
	praat_FFNet_init.c manual_FFNet.c
""")

Import ('env')
env.Library ('FFNet', sources)
