# File stat/Table.cpp.praat
# Generated by test/createPraatTests.praat

#
# Paul Boersma 2002-05-02
#
# bug reported by Michelle Porter on 2002-05-01
#

Create Table with column names: "table", 4, "A B"
Set numeric value: 1, "A", 1
Set numeric value: 2, "A", 2
Set numeric value: 3, "A", 3
Set numeric value: 4, "A", 4
Set numeric value: 1, "B", 4
Set numeric value: 2, "B", 3
Set numeric value: 3, "B", 2
Set numeric value: 4, "B", 1
Scatter plot (mark): "A", 0, 0, "B", 0, 0, 1, "yes", "+"
Remove

appendInfoLine: "stat/Table.cpp.praat", " OK"
