# File sys/Interpreter.cpp.praat
# Generated by test/createPraatTests.praat

asserterror Vector interpreter_assignToVector# does not exist.
interpreter_assignToVector# [5] = 3

asserterror Unknown variable:'newline$'« interpreter_assignToVector#
interpreter_assignToVector# = interpreter_assignToVector# + 5

asserterror The vector interpreter_assignToVector# does not exist.
interpreter_assignToVector# += 5

appendInfoLine: "sys/Interpreter.cpp.praat", " OK"
