# File sys/melder_ftoa.cpp.praat
# Generated by test/createTests.praat
# Sun Oct  8 15:07:01 2017

assert string$ (1000000000000) = "1000000000000"
assert string$ (undefined) = "--undefined--"

appendInfoLine: "sys/melder_ftoa.cpp.praat", " OK"
