# File sys/melder_ftoa.cpp.praat
# Generated by test/createTests.praat
# Mon Mar 19 16:13:50 2018

assert string$ (1000000000000) = "1000000000000"
assert string$ (undefined) = "--undefined--"

appendInfoLine: "sys/melder_ftoa.cpp.praat", " OK"
