# File sys/melder_ftoa.cpp.praat
# Generated by test/createPraatTests.praat
# Tue Jul  3 23:30:12 2018

assert string$ (1000000000000) = "1000000000000"
assert string$ (undefined) = "--undefined--"

appendInfoLine: "sys/melder_ftoa.cpp.praat", " OK"
