# File sys/praat_statistics.cpp.praat
# Generated by test/createTests.praat
# Mon Mar 19 16:13:51 2018

report$ = Report integer properties
sizeOfInteger = extractNumber (report$, "An indexing integer is ")
sizeOfPointer = extractNumber (report$, "A pointer is ")
assert sizeOfInteger = sizeOfPointer
sizeOfFileOffset = extractNumber (report$, "A file offset is ")
assert sizeOfFileOffset = 64

appendInfoLine: "sys/praat_statistics.cpp.praat", " OK"
