# LPC/SConscript
# 
#  Copyright (C) 1993-2005 David Weenink
# 
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or (at
#  your option) any later version.
# 
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
# 
# 
# 
#  djmw 20051012

lib = 'LPC'
cpppath = Split ('../dwtools ../fon ../sys ../dwsys')

sources = Split ("""
	Cepstrum.c Cepstrumc.c Cepstrum_and_Spectrum.c
	LPC.c LPC_and_Cepstrumc.c LPC_and_Formant.c LPC_and_LFCC.c
	LPC_and_Polynomial.c
	LPC_to_Spectrum.c  LPC_to_Spectrogram.c
	LPC_and_Tube.c
	Sound_and_LPC.c Sound_and_LPC_robust.c
	Sound_and_Cepstrum.c Tube.c
	praat_LPC_init.c manual_LPC.c
""")

Import ('env')
local_env = env.Copy (CPPPATH = cpppath)
objects = local_env.Object (sources)
local_env.Library (lib, objects)
